spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apex?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: true # enable file uploading
      max-file-size: 100MB # limited file size of 10 MB
  redis:
    host: localhost # Redis server address
    database: 0 # Redis index（default 0）
    port: 6379 # Redis server port no.
    password: # Redis server password（default empty）
    timeout: 300ms # ttl（ms）
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

minio:
  endpoint: https://minio.malcolmpro.com #MinIO server address
  bucketName: apex
  accessKey: minioadmin
  secretKey: minioadmin

jwt:
  tokenHeader: Authorization # JWT header for storage
  secret: secret-apex-review-of-academic-paper # The key used for JWT encryption and decryption
  expiration: 86400 # JWT expired time (seconds) (1 * 24 * 60 * 60)
  tokenHead: 'Bearer '  # The beginning in the JWT load

secure:
  ignored:
    urls: # Secure Path Whitelist
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
      - /user/logout
      - /file/upload

redis:
  database: apex
  key:
    user: 'user'
    resourceList: 'resourceList'
    authCode: 'authCode'
  expire:
    common: 604800 # 24 hours * 7 days
    authCode: 90 # auth code expire time (seconds)

bidding-system:
  url: "http://127.0.0.1:5000/bidding"