spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/apex?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  redis:
    host: default_redis # Redis server address
    database: 0 # Redis index（default 0）
    port: 6379 # Redis server port no.
    password: # Redis server password（default empty）
    timeout: 300ms # ttl（ms）

minio:
  endpoint: apex_minio:9000 #MinIO server address
  bucketName: apex
  accessKey: minioadmin
  secretKey: minioadmin

bidding-system:
  url: "http://bidding_system:5001/bidding"
